#!/usr/bin/env node
const jsdom = require('jsdom');
const commander = require("commander");
const vt2svg = require('./src/vt2svg');
const { JSDOM } = jsdom;
const body = new JSDOM().window.document.body;

commander
  .version(require("./package.json").version)
  .option('-x, --lon [lon]', 'Longitude of center')
  .option('-y, --lat [lat]', 'Lattitude of center')
  .option('-w, --width [width]', 'Width of output svg')
  .option('-h, --height [height]', 'Height of output svg')
  .option('-z, --zoom [zoom]', 'Zoom level of the view')
  .option('-l, --layers [layers]', 'Layersets')
  .option('--background [color]', 'Background Color')
  .option('--make-png', 'Add if you want to make png file')
  .option('-o, --output [filename]', 'Output file name')
  .parse(process.argv);

const state = {
  width: parseFloat(commander.width) || 256,
  height: parseFloat(commander.height) || 256,
  lon: parseFloat(commander.lon) || 140.475,
  lat: parseFloat(commander.lat) || 36.375,
  viewZoom: parseFloat(commander.zoom) || 16,
  backgroundColor: commander.background || '#fff',
  makePng: commander.makePng || false,
  layers: commander.layers || 'rdcl,railcl',
  output: commander.output || './output.svg'
};

vt2svg(body, state);
